Specified the Optuna version
Fix error: 
RuntimeError: The runtime optuna version 2.3.0 is no longer compatible with the table schema (set up by optuna 0.10.0). Please execute `$ optuna storage upgrade --storage $STORAGE_URL` for upgrading the storage. """