Update RLTrader.py
qs.report.html() signature doesn't support `file` as an argument; so, calling this results in: "TypeError: html() got an unexpected keyword argument 'file'". The correct argument is `output`.  See: https://github.com/ranaroussi/quantstats/blob/6aaa65c20bad4c364efa7623375901925c036b45/quantstats/reports.py#L57 and https://github.com/ranaroussi/quantstats/blob/6aaa65c20bad4c364efa7623375901925c036b45/quantstats/reports.py#L250